### ISSUE TITLE
tab组件未编译

### ISSUE THREAD

**Issue by bugZhang** [jimmyrogue/wepy-X-minui#1]
tab组件只编译了index.wxc，还有label和panel未编译在packages/tab/dist/目录下

**Comment by jimmyrogue** [comment]
@bugZhang 恩，组件我还没有全部添加完，昨天又加了一些。tab会加上去的。

**Comment by jimmyrogue** [comment]
@bugZhang 尝试了一下，tab组件在wepy下似乎有点问题，其他组件基本都添加了，可以看一看
