### ISSUE TITLE
请问以后会跟minUI同步更新么？

### ISSUE THREAD

**Issue by g1mi** [jimmyrogue/wepy-X-minui#4]
谢谢作者的努力，我也觉得minui的风格很是优雅，正愁怎么转到wepy上来呢，希望以后可以之一更新哟😊

**Comment by jimmyrogue** [comment]
@g1mi 恩会的，最近公司项目有点忙，等空一点了会去更新。

**Comment by g1mi** [comment]
@jimmyrogue 👍👍👍
