### ISSUE TITLE
请更明确的表述在已有的wepy项目中使用minui的相关文档。

### ISSUE THREAD

**Issue by wuzhuzhu** [jimmyrogue/wepy-X-minui#5]
在已有项目中使用 是否还需要copy所有packages里面的组件内容？
如果不需要，我理解是按需min install单个组件 然后在对应页面引入
文档中提到了min install ... 但是没有介绍min是什么... 
(https://github.com/iwillwen/mindb/blob/master/README_zhcn.md 总不会是这个吧...)
如果使用yarn代替 则watch的时候报错

```
/// import Cc from '@minui/wxc-cc'
找不到文件：..../node_modules/@minui/wxc-cc/dist/index.js
/// import Cc from '@minui/wxc-cc'
找不到文件: project/path.../src/packages/@minui/wxc-cc
```

**Comment by jimmyrogue** [comment]
@wuzhuzhu minui其实我最下面写了连接的 https://github.com/meili/minui
主要这个项目是供使用min组件和wepy的朋友参考使用
感谢提供意见。
