### ISSUE TITLE
集成项目有问题

### ISSUE THREAD

**Issue by hqsiswiliam** [jimmyrogue/wepy-X-minui#7]
已经按照作者的配置配了项目, 在项目中使用min install @miui/wxc-badge, 不过等到wepy build的时候,并没有在dist目录下看到有packages, 使用usingComponent就显示`Component is not found in path "pages/user/packages/@minui/wxc-badge/dist/index"`

**Comment by jimmyrogue** [comment]
检查一下项目里的min.config.json文件是否存在，且里面的dest属性配置的路径是否正确

**Comment by hqsiswiliam** [comment]
我最后发现是装的min-cli有问题,一开始用了`npm install -g min-cli`, 然后`min install` 出来的结果没有, 然后又试了`npm install -g min` 的 `min install`也不行, 最后是[这个仓库](https://github.com/meili/min-cli)上发现需要`npm install -g @mindev/min-cli` 安装出来的min-cli才能正常使用.
